FROM golang:1.24-alpine

WORKDIR /app

# Install air and migrate
RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Command to run air
CMD ["air", "-c", ".air.toml"]
