services:
  qp-broker-service:
    build: 
      context: ./broker-service
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${VERSION:-1.0.0}
        BUILD_DATE: ${BUILD_DATE}
        COMMIT_SHA: ${COMMIT_SHA}
    image: pariksh1th/broker-service:${VERSION:-1.0.0}
    restart: always
    environment:
      - WEB_PORT=${WEB_PORT}
      - CGO_ENABLED=0
      - DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:${WEB_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
