services:
  broker-service:
    build: 
      context: ./broker-service
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${VERSION:-1.0.0}
        BUILD_DATE: ${BUILD_DATE}
        COMMIT_SHA: ${COMMIT_SHA}
    image: broker-service:${VERSION:-1.0.0}
    restart: always
    environment:
      - WEB_PORT=80
      - CGO_ENABLED=0
    ports:
      - "8080:80"
