services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./broker-service:/app
    environment:
      - WEB_PORT=${WEB_PORT}
      - CGO_ENABLED=0
      - DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:${WEB_PORT}"
    depends_on:
      - postgres
    # Optional: enable delve debugger
    # security_opt:
    #   - "seccomp:unconfined"
    # cap_add:
    #   - SYS_PTRACE

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data:
