// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCsrfToken(ctx context.Context, arg CreateCsrfTokenParams) (CsrfToken, error)
	CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) (SessionToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSessionToken(ctx context.Context, token string) error
	GetCsrfTokenBySessionID(ctx context.Context, sessionID uuid.UUID) (CsrfToken, error)
	GetSessionTokenByToken(ctx context.Context, token string) (SessionToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error)
	UpdateUserLastActivity(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
